"use client"
import Head from "next/head";
import NavicationSubpage from "../components/NavicationSubpage";
import { useEffect,useState } from "react";
import SidebarFilter from "../components/SidebarFilter";
import Footer from "../components/Footer";


export default function Listing() {
  const [icons, setIcons] = useState([]);

  useEffect(() => {
    const fetchIcons = async () => {
      try {
        const response = await fetch('https://iconsguru.com/admin/api/icons');
        const data = await response.json();
        setIcons(data.icons); // Assuming the response contains an array of icons in `icons`
      } catch (error) {
        console.error('Error fetching icons:', error);
      }
    };

    fetchIcons();
  }, []);

  return (
      <>
      <Head>
        <title>Listing page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <NavicationSubpage/>
        <main className="conatiner-fluid">
            {/* {posts.map((post) => (
              <div key={post.id}>
                <h2>{post.title}</h2>
                <p>{post.body}</p>
              </div>
            ))} */}
            <div className="row">
                <div className="col-lg-3">
                    <SidebarFilter/>
                </div>
                <div className="col-lg-9">
                    <div className="main-divs g-col-6">
                        <div className="tabsd_divs d-inline-block w-100 mt-3 ps-lg-3">
                            <ul className="nav nav-tabs" role="tablist">
                              <li className="nav-item" role="presentation">
                                <button className="nav-link active" 
                                data-bs-toggle="tab" data-bs-target="#icons1" type="button" role="tab" aria-controls="icons1"
                                  aria-selected="true">Icons</button>
                              </li>
                              <li className="nav-item" role="presentation">
                                <button className="nav-link" data-bs-toggle="tab" data-bs-target="#interface" type="button"
                                role="tab" aria-controls="interface" aria-selected="false">Interface Icons</button>
                              </li>
                              <li className="nav-item" role="presentation">
                                <button className="nav-link"  data-bs-toggle="tab"
                                data-bs-target="#animated" type="button" role="tab" aria-controls="animated"
                                  aria-selected="false">Animated Icons</button>
                              </li>
                            </ul>
                            <div className="tab-content" id="myTabContent">
                              <div className="tab-pane fade show active" id="icons1" role="tabpanel" aria-labelledby="icons1-tab">
                                  <h4 className="search_heading mt-3"> 2,550 Bag Icons </h4>
                                  <div className="row row-cols-1 row-cols-lg-6 gy-4 g-lg-4 mt-0">
                                      
                                     
                                      {icons.length === 0 ? (
                                            <p>Icons Coming.</p>
                                          ) : (
                                            icons.map((icon) => (
                                            <div key={icon.id} className="svg-item col" >
                                                <button className="btn p-0" data-bs-toggle="modal" data-bs-target="#modaldetails"> 
                                                   <span dangerouslySetInnerHTML={{ __html: icon.icon_svg }}></span>
                                                </button>
                                            </div>
                                            ))
                                          )}
                                      
                
                                  </div>
                              </div>
                              <div className="tab-pane fade" id="interface" role="tabpanel" aria-labelledby="interface-tab">
                                  <h4 className="search_heading mt-3"> 2,550 Interface Bag Icons </h4>
                                  <div className="row row-cols-1 row-cols-lg-6 gy-4 g-lg-4 mt-0">
                                     
                
                                  </div>
                              </div>
                              <div className="tab-pane fade" id="animated" role="tabpanel" aria-labelledby="animated-tab">...</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>



        <div className="modal fade" id="modaldetails" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div className="modal-dialog modal-xl">
            <div className="modal-content">
              <div className="modal-header">
                
                <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div className="modal-body">
                   <h2> Details </h2>
              </div>
            
            </div>
          </div>
        </div>

        <Footer/>
      </>
  );
}
