"use client";
import { useEffect, useState } from "react";
import NavicationHome from "../components/NavicationHome";
import Footer from "../components/Footer";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Form from "next/form";

export default function Icons() {
  const icontypes = [
    { id: 1, title: 'Interface Essential' , counting: '200', tag:"", img: '/interface.svg', link: '/icons'  },
    { id: 2, title: 'Design' , counting: '100', tag:"New", img: '/design-th1.svg', link: '/icons'  },
    { id: 3, title: 'Food' , counting: '300', tag:"", img: '/food-th.svg', link: '/icons'  },
    { id: 4, title: 'Social' , counting: '2000', tag:"", img: '/social.svg', link: '/icons'  },
    { id: 5, title: 'Business' , counting: '1000', tag:"", img: '/business.svg', link: '/icons'  },
    { id: 6, title: 'Shopping' , counting: '1000', tag:"", img: '/shopping1.svg', link: '/icons'  },
    { id: 8, title: 'Shopping' , counting: '1000', tag:"", img: '/shopping1.svg', link: '/icons'  },
  ];

  return (
    <>
      <Head>
        <title>Icons Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavicationHome/>
      <main className="pricing-pages-part float-start w-100">
            <section className="float-start w-100 pt-0">
                  <div className="container">
                     <div className="comon-cate-list trending-icons d-inline-block w-100">
                        <div className="row align-items-center">
                            <div className="col-lg-7">
                              <div className="d-flex align-items-center">
                                  <h2 className="text-left comon-head cmg-heading m-0"> Trending Icon packs </h2> 
                                  <span className="ms-2 style-list01">43 styles </span>
                              </div>
                            </div>
                            
                        </div>
                             
                        <div className="row row-cols-1 row-cols-lg-3 gy-4 g-lg-4 mt-4">
      
                            {icontypes.map((type) => (
                                    <div className="col" key={type.id}>
                                      <article className="d-inline-block w-100 comon-types01 position-relative">
                                      <span className="tagsd">{type.tag}</span>
                                        <figure className="text-center mx-auto d-block mb-1">
                                          <Link href={type.link}> <Image loading="lazy" src={type.img}
                                                alt="user"
                                                width={260}
                                                height={178} /> </Link>
                                        </figure>
                                        <span className="d-flex icon-list-name col-lg-10 mx-auto align-items-center justify-content-between">
                                            <h5 className="mb-0"> 
                                              <Link href={type.link}> 
                                                {type.title}
                                              </Link>
                                            </h5>
                                            <Link className="coun-text" href={type.link}> 
                                                
                                              <strong> {type.counting}</strong> icons
                                            </Link>
                                            
                                        </span>
                                      </article>
                                    </div>
                                ))}
                            
                        </div>
                     </div>

                     <div className="comon-cate-list lis-icou-page05 d-inline-block w-100">
                        <div className="row align-items-center">
                            <div className="col-lg-7">
                              <div className="d-flex align-items-center">
                                  <h2 className="text-left comon-head cmg-heading m-0"> Trending Icon packs </h2> 
                                  <span className="ms-2 style-list01">43 styles </span>
                              </div>
                            </div>
                            
                        </div>
      
                        <div className="row row-cols-1 row-cols-lg-3 gy-4 g-lg-4 mt-4">
      
                            {icontypes.map((type) => (
                                    <div className="col" key={type.id}>
                                      <article className="d-inline-block w-100 comon-types01 position-relative">
                                      <span className="tagsd">{type.tag}</span>
                                        <figure className="text-center mx-auto d-block mb-1">
                                          <Link href={type.link}> <Image loading="lazy" src={type.img}
                                                alt="user"
                                                width={260}
                                                height={178} /> </Link>
                                        </figure>
                                        <span className="d-flex icon-list-name col-lg-10 mx-auto align-items-center justify-content-between">
                                            <h5 className="mb-0"> 
                                              <Link href={type.link}> 
                                                {type.title}
                                              </Link>
                                            </h5>
                                            <Link className="coun-text" href={type.link}> 
                                                
                                              <strong> {type.counting}</strong> icons
                                            </Link>
                                            
                                        </span>
                                      </article>
                                    </div>
                                ))}
                            
                        </div>
                     </div>
      
                  </div>
             </section>
       </main>

      <Footer/>
    </>
  );
}
