import { Sora, Play, Playfair, Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import ImportBsJS from "../app/components/ImportBsJS";


const sorasans = Sora({
  variable: "--font-sora-sans",
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

const play = Play({
  variable: "--font-play-sans",
  weight: ['700'],
  subsets: ['latin'],
});

const playfa = Playfair({
  variable: "--font-playfa-sans",
  weight: ['400'],
  subsets: ['latin'],
});

const inter = Inter({
  variable: "--font-inter-sans",
  weight: ['800'],
  subsets: ['latin'],
});







export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <body>
      <style>{`
        html {
          font-family: ${sorasans.style.fontFamily};
        }
        .banner-parts01 h2{
         font-family: ${sorasans.style.fontFamily};
        }
        button{
         font-family: ${inter.style.fontFamily};
        } 
        input{
         font-family: ${sorasans.style.fontFamily};
        }
         h5.sub-headings{
           font-family: ${play.style.fontFamily};
         }
        p.text-para1{
          font-family: ${playfa.style.fontFamily};
        }
        h2.comon-head,
        .comon-types01 h5 a,
        .coun-text,
        .btn,
        p,
        h5,
        .icon-headings,
        .styles-icons-div h4,
        .comon-heading-sub{
          font-family: ${inter.style.fontFamily};
        }
         
        
      `}
    </style>
        <ImportBsJS/>
        {children}
      </body>
    </html>
  );
}
