import { Geist, Geist_Mono, Sora } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import ImportBsJS from "../app/components/ImportBsJS";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sorasans = Sora({
  variable: "--font-sora-sans",
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <style>{`
        html {
          font-family: ${sorasans.style.fontFamily};
        }
        h1, h2, h3, h4, h5{
         font-family: ${sorasans.style.fontFamily};
        }
        button{
         font-family: ${sorasans.style.fontFamily};
        } 
        a, p, input{
         font-family: ${sorasans.style.fontFamily};
        }
        
      `}
    </style>
        <ImportBsJS/>
        {children}
      </body>
    </html>
  );
}
