"use client";
import { useState, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import Head from "next/head";
import NavicationSubpage from "../components/NavicationSubpage";
import Footer from "../components/Footer";

export default function NewSearchResults() {


  return (
    <>
      <Head>
        <title>Search Results</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavicationSubpage />
    
      <Footer />
    </>
  );
}
